apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}-config
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
data:
  default-config.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
      <bean class="org.apache.ignite.configuration.IgniteConfiguration">
        <property name="peerClassLoadingEnabled" value="{{ .Values.peerClassLoadingEnabled }}"/>
        <property name="discoverySpi">
          <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
            <property name="ipFinder">
              <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                <property name="namespace" value="{{ .Release.Namespace }}"/>
                <property name="serviceName" value="{{ include "ignite.fullname" . }}"/>
              </bean>
            </property>
          </bean>
        </property>
{{- if .Values.persistence.enabled }}
        <property name="dataStorageConfiguration">
          <bean class="org.apache.ignite.configuration.DataStorageConfiguration">
            <property name="defaultDataRegionConfiguration">
              <bean class="org.apache.ignite.configuration.DataRegionConfiguration">
                <property name="persistenceEnabled" value="true"/>
              </bean>
            </property>
            <property name="storagePath" value="/persistence"/>
            <property name="walPath" value="/persistence/wal"/>
            <property name="walArchivePath" value="/persistence/wal-archive"/>
          </bean>
        </property>
{{- end }}
      </bean>
    </beans>
