apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "ignite.selectorLabels" . | nindent 4 }}
  ports:
    - name: communication
      port: 47100
    - name: discovery
      port: 47500
    - name: thin-client
      port: 10800
    - name: rest
      port: 8080
    - name: jmx
      port: 49112
