{{- if and (not .Values.config.existing.certificates) (gt (len .Values.config.certificates) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver.certificateSecretName" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  {{- toYaml .Values.config.certificates | nindent 2 }}
{{- end }}
