{{- if and (not .Values.config.existing.core) (not .Values.config.existing.coreSecret) (or .Values.config.core .Values.config.generated) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver.coreConfigName" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  {{ .Values.config.existing.coreSecretKey | quote }}: |-
{{- if .Values.config.core }}
    {{- tpl .Values.config.core . | nindent 4 }}
{{- else }}
    {{- tpl (.Files.Get "files/CoreConfig.xml") . | nindent 4 }}
{{- end }}
{{- end }}
