{{- if not .Values.database.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "takserver.databaseSecretName" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  {{ .Values.database.auth.secretKeys.database | quote }}: {{ .Values.database.auth.database | quote }}
  {{ .Values.database.auth.secretKeys.username | quote }}: {{ .Values.database.auth.username | quote }}
  {{ .Values.database.auth.secretKeys.password | quote }}: {{ .Values.database.auth.password | quote }}
{{- end }}
