{{- if .Values.serviceAccount.create }}
{{- $annotations := mergeOverwrite (dict) .Values.commonAnnotations .Values.serviceAccount.annotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "takserver.serviceAccountName" . }}
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
{{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
