{{- $serviceType := "ClusterIP" -}}
{{- if eq .Values.exposure.mode "service" }}{{- $serviceType = .Values.exposure.service.type }}{{- end }}
{{- $serviceAnnotations := mergeOverwrite (dict) .Values.commonAnnotations .Values.exposure.service.annotations -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "takserver.fullname" . }}-api
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- with $serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $serviceType }}
  selector:
    {{- include "takserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: https-8443
      port: 8443
      targetPort: https-8443
    - name: fed-8444
      port: 8444
      targetPort: fed-8444
    - name: certs-8446
      port: 8446
      targetPort: certs-8446
    - name: http-8080
      port: 8080
      targetPort: http-8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "takserver.fullname" . }}-messaging
  labels:
    {{- include "takserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
{{- with $serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ $serviceType }}
  selector:
    {{- include "takserver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
  ports:
    - name: tls-8089
      port: 8089
      targetPort: tls-8089
    - name: fedv1-9000
      port: 9000
      targetPort: fedv1-9000
    - name: fedv2-9001
      port: 9001
      targetPort: fedv2-9001
