{{- if and .Values.traefik.enabled .Values.traefikRoutes.enabled }}
{{- $fullname := include "takserver.fullname" . -}}
{{- $routes := list
  (dict "name" "api" "entryPoint" "websecure" "service" (printf "%s-api" $fullname) "port" 8443)
  (dict "name" "federation-api" "entryPoint" "takfed" "service" (printf "%s-api" $fullname) "port" 8444)
  (dict "name" "certificate-api" "entryPoint" "takcerts" "service" (printf "%s-api" $fullname) "port" 8446)
  (dict "name" "cot" "entryPoint" "takcot" "service" (printf "%s-messaging" $fullname) "port" 8089)
  (dict "name" "federation-v1" "entryPoint" "fedv1" "service" (printf "%s-messaging" $fullname) "port" 9000)
  (dict "name" "federation-v2" "entryPoint" "fedv2" "service" (printf "%s-messaging" $fullname) "port" 9001)
-}}
{{- range $route := $routes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullname }}-{{ $route.name }}
  labels:
    {{- include "takserver.labels" $ | nindent 4 }}
{{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  entryPoints:
    - {{ $route.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ $route.service }}
          port: {{ $route.port }}
  tls:
    passthrough: true
---
{{- end }}
{{- end }}
