{{- $fullname := include "takserver.fullname" . -}}
{{- include "takserver.traefikIngressRouteTCP" (dict "root" . "route" (dict
  "name" "api" "entryPoint" "websecure" "service" (printf "%s-api" $fullname) "port" 8443
)) }}
