{{- $fullname := include "takserver.fullname" . -}}
{{- include "takserver.traefikIngressRouteTCP" (dict "root" . "route" (dict
  "name" "certificate-api" "entryPoint" "takcerts" "service" (printf "%s-api" $fullname) "port" 8446
)) }}
