{{- if .Values.serviceAccount.create }}
{{- $annotations := mergeOverwrite (dict) .Values.commonAnnotations .Values.serviceAccount.annotations }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ignite.serviceAccountName" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
{{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
{{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ignite.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "ignite.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
