apiVersion: v2
name: ignite
description: TAK-compatible Apache Ignite server nodes.
type: application
version: 0.1.0
appVersion: "2.17.0"
kubeVersion: ">=1.27.0-0"
home: https://github.com/jeremymcgee73/Server
icon: https://raw.githubusercontent.com/jeremymcgee73/Server/main/src/federation-hub-ui/src/main/webapp-angular/public/tak-logo.png
sources:
  - https://github.com/jeremymcgee73/Server
maintainers:
  - name: jeremymcgee73
    url: https://github.com/jeremymcgee73
